# This defines a pipeline to build on Windows, Linux, and macOS in Release mode.

trigger: none

stages:
  - stage: build
    displayName: Build
    jobs:
    - template: jobs.yaml
      parameters:
        debug: false
        name: Windows
    # - template: jobs.yaml
    #   parameters:
    #     debug: false
    #     name: Linux
    - template: jobs.yaml
      parameters:
        debug: false
        name: macOS
    - template: jobs.yaml
      parameters:
        debug: false
        name: Android
    - template: jobs.yaml
      parameters:
        debug: false
        name: iOS
