
trigger:
- main

pool:
  vmImage: windows-latest

variables:
  CodeQL.Enabled: true
  LGTM.UploadSnapshot: true

steps:
- task: CMake@1
  displayName: 'Configure SEAL'
  inputs:
    cmakeArgs: -S . -B build -DCMAKE_BUILD_TYPE=${{ parameters.configuration }} -DSEAL_BUILD_DEPS=ON -DSEAL_BUILD_TESTS=ON -DSEAL_BUILD_EXAMPLES=ON -DSEAL_BUILD_SEAL_C=ON -DSEAL_SECURE_COMPILE_OPTIONS=ON
    workingDirectory: '$(Build.SourcesDirectory)/build'

- task: DotNetCoreCLI@2
  displayName: 'Build Solution'
  inputs:
    command: 'build'
    projects: 'PairMeWebsite.sln'
    arguments: '--configuration Release --no-restore'

- task: CredScan@3
  displayName: 'Credential Scan'

- task: CodeQL3000Init@0
- task: CodeQL3000Finalize@0

- task: ComponentGovernanceComponentDetection@0
  inputs:
    scanType: 'Register'
    verbosity: 'Verbose'
    alertWarningLevel: 'High'

- task: PublishSecurityAnalysisLogs@3
  inputs:
    ArtifactName: 'CodeAnalysisLogs'
    ArtifactType: 'Container'
    PublishProcessedResults: true
    AllTools: true
    ToolLogsNotFoundAction: 'Standard'
